### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by jikuja** [pwk4m1/REWORKSHOP#1]
For starters using GCC flags -O0 and -fno-pie might be worth of consideration. 

I also noticed that GCC will eliminate dead code like printf calls in https://github.com/pwk4m1/REWORKSHOP/blob/master/Code/ready/medium_difficulty/crack_me_ez_one/src/crack_me_if_you_can.c#L34 That makes getting flag from binary impossible even if you find out correct key.

**Comment by pwk4m1** [comment]
Thnx for letting me know! I apparently forgot to add no optimization flags to makefile, will update asap!

**Comment by jikuja** [comment]
Probably similar dead code elimination problem here: https://github.com/pwk4m1/REWORKSHOP/blob/master/Code/ready/hard_difficulty/crack_me/src/crack_me.c#L259-L265 Compile with `gcc -g -Wall -O0 -fno-pie -o bin/crack_me src/crack_me.c` gives really short finit function.

Using `-O0` does not disable all dead code elimination optimizations :/

**Comment by pwk4m1** [comment]
Oh, well damnit! Should've done more testing before release.. but due awefully busy time I was having had no time for that ;_;

I'll fix the issue /code during today/tomorrow &notify people about my lil fuckup.

**Comment by pwk4m1** [comment]
Code should be fixed now. Thnx a lot for poking me about this!
